added debian install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -30,15 +30,54 @@ install_fswatch() {
   fi
 }
 
+check_os_is_debian() {
+  (cat /proc/version | grep "Debian") >/dev/null
+  debian_result=$?
+  if [[ $debian_result -eq 0 ]]; then
+    echo "OS is Debian OK"
+  else
+    echo "I only know how to install for Debian, and you're not debian :-("
+    exit 1
+  fi
+}
+
+install_inotify_tools() {
+  (dpkg -l | grep inotify-tools) >/dev/null
+  inotify_tools_installed_result=$?
+  if [[ $inotify_tools_installed_result -eq 0 ]]; then
+    echo "inotify-tools is already installed OK"
+  else
+    echo "About to install inotify-tools..."
+    sudo apt install inotify-tools
+    install_inotify_tools_result=$?
+
+    if [[ $install_inotify_tools_result -eq 0 ]]; then
+      echo "Installed inotify-tools OK"
+    else
+      echo "Failed to install inotify-tools :-( fail. You're on your own now :-("
+      exit 1
+    fi
+  fi
+}
+
 install_for_mac() {
   check_brew_is_installed
   install_fswatch
   echo "Everything installed OK"
 }
 
+install_for_debian() {
+  check_os_is_debian
+  install_inotify_tools
+  echo "Everything installed OK"
+}
+
 case $OSTYPE in
   'darwin20')
     install_for_mac
+    ;;
+  'linux-gnu')
+    install_for_debian
     ;;
   *)
     echo "Installing on your OS $OSTYPE is not yet supported :-("
